export type Moment =
  | "bedtime"
  | "travel"
  | "calm"
  | "sick-day"
  | "restaurant"
  | "learning"
  | "active"
  | "morning";

export type AgeGroup = "1-2" | "2-3" | "3-4" | "4-5" | "5-6" | "all";

export interface ContentItem {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  duration: string;
  ageGroups: AgeGroup[];
  moments: Moment[];
  youtubeId: string;
  parentRating: number;
  parentReviews: number;
  tags: string[];
  workedFor: number;
  addedBy: string;
}

export interface Playlist {
  id: string;
  title: string;
  description: string;
  cover: string;
  coverEmoji: string;
  moments: Moment[];
  ageGroups: AgeGroup[];
  itemCount: number;
  saves: number;
  createdBy: string;
  parentVerified: boolean;
  tags: string[];
  gradient: string;
  items?: ContentItem[];
}

export const MOMENTS: { id: Moment; label: string; emoji: string; color: string; bg: string }[] = [
  { id: "bedtime", label: "Bedtime Wind-Down", emoji: "🌙", color: "#7C3AED", bg: "#EDE9FE" },
  { id: "travel", label: "Travel & Flights", emoji: "✈️", color: "#0284C7", bg: "#E0F2FE" },
  { id: "calm", label: "Calm & Reset", emoji: "🌿", color: "#059669", bg: "#D1FAE5" },
  { id: "sick-day", label: "Sick Day Comfort", emoji: "🤒", color: "#DC2626", bg: "#FEE2E2" },
  { id: "restaurant", label: "Restaurant Wait", emoji: "🍕", color: "#D97706", bg: "#FEF3C7" },
  { id: "learning", label: "Learning & Growth", emoji: "📚", color: "#2563EB", bg: "#DBEAFE" },
  { id: "active", label: "Move & Dance", emoji: "💃", color: "#DB2777", bg: "#FCE7F3" },
  { id: "morning", label: "Morning Start", emoji: "☀️", color: "#CA8A04", bg: "#FEF9C3" },
];

export const AGE_GROUPS: { id: AgeGroup; label: string }[] = [
  { id: "all", label: "All Ages" },
  { id: "1-2", label: "1–2 yrs" },
  { id: "2-3", label: "2–3 yrs" },
  { id: "3-4", label: "3–4 yrs" },
  { id: "4-5", label: "4–5 yrs" },
  { id: "5-6", label: "5–6 yrs" },
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: "bedtime-wind-down-2yr",
    title: "2-Year-Old Bedtime Wind-Down",
    description: "Calm songs, slow animations, and gentle routines that actually work for toddler bedtime. Parents in our community swear by these.",
    cover: "/playlists/bedtime.jpg",
    coverEmoji: "🌙",
    moments: ["bedtime"],
    ageGroups: ["1-2", "2-3"],
    itemCount: 4,
    saves: 847,
    createdBy: "Sarah M., mom of 3",
    parentVerified: true,
    tags: ["calm", "sleep", "routine", "lullabies"],
    gradient: "from-indigo-500 to-purple-600",
    items: [
      {
        id: "twinkle-ssl",
        title: "Twinkle Twinkle Little Star",
        description: "Gentle classic lullaby with soft animations — perfect for winding down before sleep.",
        thumbnail: "⭐",
        duration: "3 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime"],
        youtubeId: "yCjJyiqpAuU",
        parentRating: 4.8,
        parentReviews: 1240,
        tags: ["lullaby", "calm", "bedtime"],
        workedFor: 91,
        addedBy: "Sarah M.",
      },
      {
        id: "goodnight-lbb",
        title: "Goodnight Baby | Lullaby for Babies to Go to Sleep",
        description: "Soft, slow lullaby with gentle visuals designed to ease babies into sleep.",
        thumbnail: "🌙",
        duration: "35 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime"],
        youtubeId: "veoh5KPOlSM",
        parentRating: 4.7,
        parentReviews: 893,
        tags: ["lullaby", "sleep", "gentle"],
        workedFor: 88,
        addedBy: "Priya N.",
      },
      {
        id: "ms-rachel-lullaby",
        title: "Songs for Littles – Lullabies | Ms. Rachel",
        description: "Speech therapist-approved bedtime songs. Slow, language-rich, and genuinely calming.",
        thumbnail: "🎵",
        duration: "20 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime", "learning"],
        youtubeId: "NsEJGgXYm5s",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["speech", "language", "lullaby", "educational"],
        workedFor: 94,
        addedBy: "Sarah M.",
      },
      {
        id: "cocomelon-bedtime-songs",
        title: "CoComelon — Bedtime Songs Compilation",
        description: "Soft CoComelon bedtime songs only — skips the energetic ones that backfire at 8pm.",
        thumbnail: "🌙",
        duration: "25 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime"],
        youtubeId: "CQoUTmJdnMo",
        parentRating: 4.2,
        parentReviews: 3201,
        tags: ["bedtime", "songs", "routine"],
        workedFor: 81,
        addedBy: "Priya N.",
      },
    ],
  },
  {
    id: "flight-safe-toddler",
    title: "Flight-Safe Toddler Videos",
    description: "Holds attention 30+ minutes. These videos worked on a 6-hour flight with a 2-year-old. No WiFi needed for some!",
    cover: "/playlists/travel.jpg",
    coverEmoji: "✈️",
    moments: ["travel"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 1243,
    createdBy: "James K., dad of 2",
    parentVerified: true,
    tags: ["travel", "offline", "long-form", "distraction"],
    gradient: "from-sky-400 to-blue-600",
    items: [
      {
        id: "baby-shark-travel",
        title: "Baby Shark Dance | Pinkfong",
        description: "Mega-popular, impossibly catchy — guaranteed to hold attention on any flight.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["travel", "active"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["catchy", "fun", "travel"],
        workedFor: 92,
        addedBy: "James K.",
      },
      {
        id: "wheels-bus-ssl",
        title: "Wheels on the Bus | Super Simple Songs",
        description: "The classic travel song with calm, clear animation — great for planes and road trips.",
        thumbnail: "🚌",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["travel", "morning"],
        youtubeId: "GbpO_RDpZeM",
        parentRating: 4.6,
        parentReviews: 2310,
        tags: ["classic", "travel", "songs"],
        workedFor: 87,
        addedBy: "Maria L.",
      },
      {
        id: "blippi-airport",
        title: "Blippi Explores the Airport | Learning for Kids",
        description: "Blippi walks through an airport — perfect travel companion that keeps kids engaged mid-flight.",
        thumbnail: "✈️",
        duration: "18 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["travel", "learning"],
        youtubeId: "s5-Bh5wW78Q",
        parentRating: 4.4,
        parentReviews: 1450,
        tags: ["blippi", "educational", "travel"],
        workedFor: 83,
        addedBy: "James K.",
      },
      {
        id: "pinkfong-nursery",
        title: "Best Nursery Rhymes Collection | Pinkfong",
        description: "45-minute compilation of nursery rhymes — long enough for most flights.",
        thumbnail: "🎶",
        duration: "45 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["travel", "calm"],
        youtubeId: "kRj0CzM_G4E",
        parentRating: 4.3,
        parentReviews: 1870,
        tags: ["nursery", "compilation", "travel"],
        workedFor: 80,
        addedBy: "David R.",
      },
    ],
  },
  {
    id: "calm-down-videos",
    title: "Videos That Calm Tantrums",
    description: "When your toddler is overstimulated or melting down. Breathing songs, slow clips, soft animations — all parent-tested.",
    cover: "/playlists/calm.jpg",
    coverEmoji: "🌿",
    moments: ["calm"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 692,
    createdBy: "Priya N., mom of twins",
    parentVerified: true,
    tags: ["tantrum", "calm", "regulation", "breathing"],
    gradient: "from-emerald-400 to-teal-600",
    items: [
      {
        id: "cosmic-kids-calm",
        title: "Cosmic Kids Yoga — Calm Down Adventure",
        description: "Yoga adventures that calm kids and stretch them out. Amazing for after tantrums.",
        thumbnail: "🧘",
        duration: "20 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["calm", "bedtime", "active"],
        youtubeId: "HcmHMXJx7xY",
        parentRating: 4.7,
        parentReviews: 1567,
        tags: ["yoga", "calm", "movement", "breathing"],
        workedFor: 89,
        addedBy: "Maria L.",
      },
      {
        id: "breathing-exercise-kids",
        title: "Belly Breathing for Kids | GoNoodle",
        description: "Simple guided breathing exercise for toddlers. Works during and after meltdowns.",
        thumbnail: "🌬️",
        duration: "3 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["calm"],
        youtubeId: "RVA2N6tX2cg",
        parentRating: 4.6,
        parentReviews: 980,
        tags: ["breathing", "calm", "regulation"],
        workedFor: 86,
        addedBy: "Priya N.",
      },
      {
        id: "ms-rachel-calm",
        title: "Calm Down Songs | Songs for Littles – Ms. Rachel",
        description: "Soft, slow songs for toddlers who need to reset. Language-rich and incredibly soothing.",
        thumbnail: "🎵",
        duration: "15 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["calm", "bedtime"],
        youtubeId: "NsEJGgXYm5s",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["calm", "language", "songs"],
        workedFor: 94,
        addedBy: "Sarah M.",
      },
      {
        id: "lbb-gentle",
        title: "Gentle Lullabies & Soft Songs | Little Baby Bum",
        description: "Slow, gentle animations and songs — the visual pacing alone helps calm overstimulated toddlers.",
        thumbnail: "🍃",
        duration: "30 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["calm", "bedtime"],
        youtubeId: "veoh5KPOlSM",
        parentRating: 4.4,
        parentReviews: 1120,
        tags: ["gentle", "lullaby", "calm"],
        workedFor: 82,
        addedBy: "Amy T.",
      },
    ],
  },
  {
    id: "sick-day-gentle",
    title: "Low-Stim Sick Day Shows",
    description: "Gentle, quiet, comforting shows toddlers watch without getting wound up. Perfect when your little one is home sick.",
    cover: "/playlists/sickday.jpg",
    coverEmoji: "🤒",
    moments: ["sick-day"],
    ageGroups: ["1-2", "2-3", "3-4", "4-5"],
    itemCount: 4,
    saves: 534,
    createdBy: "Maria L., mom of 1",
    parentVerified: true,
    tags: ["gentle", "quiet", "comforting", "low-stim"],
    gradient: "from-rose-400 to-pink-600",
    items: [
      {
        id: "sick-day-lbb",
        title: "Nursery Rhymes & Baby Songs | Little Baby Bum",
        description: "Gentle animations and classic songs. Low-stimulation, comforting on sick days.",
        thumbnail: "🎈",
        duration: "40 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["sick-day", "calm"],
        youtubeId: "veoh5KPOlSM",
        parentRating: 4.5,
        parentReviews: 1340,
        tags: ["gentle", "comforting", "calm"],
        workedFor: 84,
        addedBy: "Maria L.",
      },
      {
        id: "twinkle-sick",
        title: "Twinkle Twinkle & Bedtime Songs | Super Simple Songs",
        description: "Soft and quiet. Good for sick days when you want something calm, not exciting.",
        thumbnail: "⭐",
        duration: "20 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["sick-day", "bedtime"],
        youtubeId: "yCjJyiqpAuU",
        parentRating: 4.7,
        parentReviews: 1120,
        tags: ["quiet", "gentle", "bedtime"],
        workedFor: 90,
        addedBy: "Amy T.",
      },
      {
        id: "ms-rachel-sick",
        title: "Cozy Learning Songs | Ms. Rachel",
        description: "Gentle, educational, and speech-friendly. Perfect for sick days at home on the couch.",
        thumbnail: "🎵",
        duration: "25 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["sick-day", "learning"],
        youtubeId: "NsEJGgXYm5s",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["gentle", "educational", "comforting"],
        workedFor: 93,
        addedBy: "Sarah M.",
      },
      {
        id: "pinkfong-slow",
        title: "Slow & Calm Nursery Rhymes | Pinkfong",
        description: "Slow-paced, familiar songs. Sick toddlers respond to these without getting wound up.",
        thumbnail: "🌸",
        duration: "30 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["sick-day", "calm"],
        youtubeId: "kRj0CzM_G4E",
        parentRating: 4.3,
        parentReviews: 760,
        tags: ["calm", "sick-day", "familiar"],
        workedFor: 79,
        addedBy: "David R.",
      },
    ],
  },
  {
    id: "restaurant-quick-wins",
    title: "5-Minute Restaurant Savers",
    description: "Short, engaging videos for when food is delayed and the meltdown is coming. Calm, not hyper. Tested in real restaurants.",
    cover: "/playlists/restaurant.jpg",
    coverEmoji: "🍕",
    moments: ["restaurant"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 421,
    createdBy: "David R., dad of 3",
    parentVerified: true,
    tags: ["quick", "engaging", "calm", "public"],
    gradient: "from-amber-400 to-orange-500",
    items: [
      {
        id: "baby-shark-restaurant",
        title: "Baby Shark Dance | Pinkfong",
        description: "Works every time. Short, catchy, and perfect for filling a 3-minute wait.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["restaurant", "travel"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["quick", "catchy", "restaurant"],
        workedFor: 92,
        addedBy: "David R.",
      },
      {
        id: "finger-family-restaurant",
        title: "Finger Family Song | Pinkfong Baby Songs",
        description: "Interactive finger song. Keeps little hands busy and eyes focused while waiting for food.",
        thumbnail: "👆",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["restaurant"],
        youtubeId: "kOJGNMXpR4U",
        parentRating: 4.3,
        parentReviews: 890,
        tags: ["interactive", "short", "restaurant"],
        workedFor: 81,
        addedBy: "Maria L.",
      },
      {
        id: "wheels-restaurant",
        title: "Wheels on the Bus | Super Simple Songs",
        description: "Short, familiar song they know. Great for grabbing attention quickly in public.",
        thumbnail: "🚌",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["restaurant", "travel"],
        youtubeId: "GbpO_RDpZeM",
        parentRating: 4.6,
        parentReviews: 2310,
        tags: ["familiar", "short", "restaurant"],
        workedFor: 85,
        addedBy: "Amy T.",
      },
      {
        id: "gonoodle-quick",
        title: "Quick Focus Song | GoNoodle",
        description: "A short, calming GoNoodle song that resets attention without ramping kids up.",
        thumbnail: "🎯",
        duration: "4 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["restaurant", "calm"],
        youtubeId: "RVA2N6tX2cg",
        parentRating: 4.4,
        parentReviews: 670,
        tags: ["calm", "quick", "focus"],
        workedFor: 80,
        addedBy: "James K.",
      },
    ],
  },
  {
    id: "abc-123-adventures",
    title: "ABC & 123 Adventures",
    description: "Learning letters, numbers, and early concepts through songs and stories that kids actually want to watch again and again.",
    cover: "/playlists/learning.jpg",
    coverEmoji: "📚",
    moments: ["learning"],
    ageGroups: ["2-3", "3-4", "4-5"],
    itemCount: 5,
    saves: 976,
    createdBy: "Teacher Jen, mom of 2",
    parentVerified: true,
    tags: ["educational", "letters", "numbers", "songs"],
    gradient: "from-blue-500 to-violet-600",
    items: [
      {
        id: "abc-ssl",
        title: "ABC Song | Super Simple Songs",
        description: "The definitive ABC song for toddlers. Clear, slow, perfect for early letter learning.",
        thumbnail: "🔤",
        duration: "2 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["learning", "morning"],
        youtubeId: "36IBDpTRVNE",
        parentRating: 4.7,
        parentReviews: 2100,
        tags: ["letters", "abc", "educational"],
        workedFor: 90,
        addedBy: "Teacher Jen",
      },
      {
        id: "numbers-ssl",
        title: "Numbers Song 1–10 | Super Simple Songs",
        description: "Learn counting 1-10 with a catchy song and bright animation. Parents love how sticky it is.",
        thumbnail: "🔢",
        duration: "3 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["learning"],
        youtubeId: "DR-cfDsHCGA",
        parentRating: 4.6,
        parentReviews: 1780,
        tags: ["numbers", "counting", "educational"],
        workedFor: 88,
        addedBy: "Teacher Jen",
      },
      {
        id: "colors-blippi",
        title: "Learn Colors with Blippi | Educational Videos for Kids",
        description: "Blippi introduces colors through real objects and play. Kids absorb it without realizing they're learning.",
        thumbnail: "🎨",
        duration: "17 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["learning"],
        youtubeId: "_7FuIFfXhvE",
        parentRating: 4.5,
        parentReviews: 1340,
        tags: ["colors", "blippi", "educational"],
        workedFor: 85,
        addedBy: "James K.",
      },
      {
        id: "shapes-ssl",
        title: "Shapes Song | Super Simple Songs",
        description: "Shapes made fun and simple. Great companion to drawing activities.",
        thumbnail: "🔷",
        duration: "2 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["learning"],
        youtubeId: "OEbRDtCAFdU",
        parentRating: 4.5,
        parentReviews: 980,
        tags: ["shapes", "educational", "songs"],
        workedFor: 83,
        addedBy: "Maria L.",
      },
      {
        id: "phonics-ssl",
        title: "Phonics Song with Two Words | A For Apple",
        description: "Best phonics song for early readers. Clear letter-sound connections kids actually remember.",
        thumbnail: "🍎",
        duration: "3 min",
        ageGroups: ["3-4", "4-5"],
        moments: ["learning"],
        youtubeId: "BELlZKpi1Zs",
        parentRating: 4.7,
        parentReviews: 1560,
        tags: ["phonics", "letters", "reading"],
        workedFor: 89,
        addedBy: "Teacher Jen",
      },
    ],
  },
  {
    id: "dance-and-wiggle",
    title: "Dance & Wiggle Time",
    description: "Get the energy OUT before it gets chaotic. Fun, silly dance videos that turn the living room into a dance floor.",
    cover: "/playlists/dance.jpg",
    coverEmoji: "💃",
    moments: ["active"],
    ageGroups: ["1-2", "2-3", "3-4", "4-5", "5-6"],
    itemCount: 4,
    saves: 1102,
    createdBy: "Community Pick",
    parentVerified: true,
    tags: ["energy", "dancing", "movement", "fun"],
    gradient: "from-pink-500 to-fuchsia-600",
    items: [
      {
        id: "baby-shark-dance",
        title: "Baby Shark Dance | Pinkfong",
        description: "The ultimate toddler dance song. Gets every kid up and moving every single time.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["active", "travel"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["dance", "movement", "fun"],
        workedFor: 95,
        addedBy: "Community Pick",
      },
      {
        id: "gonoodle-dance",
        title: "Jump & Dance | GoNoodle",
        description: "GoNoodle's movement videos are perfect for burning energy before dinner or at the park.",
        thumbnail: "💃",
        duration: "5 min",
        ageGroups: ["2-3", "3-4", "4-5", "5-6"],
        moments: ["active"],
        youtubeId: "l4WNrvVjiTw",
        parentRating: 4.7,
        parentReviews: 1450,
        tags: ["movement", "dance", "energy"],
        workedFor: 91,
        addedBy: "Amy T.",
      },
      {
        id: "head-shoulders",
        title: "Head Shoulders Knees & Toes | Super Simple Songs",
        description: "Classic action song that gets little bodies moving. Works from 1 to 6 years.",
        thumbnail: "🙌",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4", "4-5"],
        moments: ["active", "morning"],
        youtubeId: "ZanHgPprl-0",
        parentRating: 4.6,
        parentReviews: 1830,
        tags: ["action", "movement", "classic"],
        workedFor: 88,
        addedBy: "Maria L.",
      },
      {
        id: "freeze-dance",
        title: "Freeze Dance for Kids | Moose Tube",
        description: "Dance and freeze on command — great for teaching body control while burning energy.",
        thumbnail: "🕺",
        duration: "6 min",
        ageGroups: ["2-3", "3-4", "4-5", "5-6"],
        moments: ["active"],
        youtubeId: "25QyCxVkXwQ",
        parentRating: 4.5,
        parentReviews: 1020,
        tags: ["freeze-dance", "movement", "fun"],
        workedFor: 87,
        addedBy: "David R.",
      },
    ],
  },
  {
    id: "morning-start-up",
    title: "Happy Morning Starter",
    description: "Cheerful, energizing shows that set a positive tone without the chaos. Great for the TV-while-getting-dressed window.",
    cover: "/playlists/morning.jpg",
    coverEmoji: "☀️",
    moments: ["morning"],
    ageGroups: ["2-3", "3-4", "4-5", "5-6"],
    itemCount: 4,
    saves: 388,
    createdBy: "Amy T., mom of 2",
    parentVerified: true,
    tags: ["morning", "cheerful", "routine", "positive"],
    gradient: "from-yellow-400 to-orange-400",
    items: [
      {
        id: "good-morning-ssl",
        title: "Good Morning Song | Super Simple Songs",
        description: "Cheerful morning song that starts the day right. Kids love the routine of it.",
        thumbnail: "☀️",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["morning"],
        youtubeId: "CuCPSRPqMnE",
        parentRating: 4.6,
        parentReviews: 1120,
        tags: ["morning", "routine", "cheerful"],
        workedFor: 85,
        addedBy: "Amy T.",
      },
      {
        id: "wheels-morning",
        title: "Wheels on the Bus | Super Simple Songs",
        description: "Gets kids ready to 'go' — great backdrop for getting dressed and eating breakfast.",
        thumbnail: "🚌",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["morning", "travel"],
        youtubeId: "GbpO_RDpZeM",
        parentRating: 4.6,
        parentReviews: 2310,
        tags: ["morning", "classic", "cheerful"],
        workedFor: 83,
        addedBy: "James K.",
      },
      {
        id: "blippi-morning",
        title: "Blippi Learns About Trucks | Educational Morning Video",
        description: "Blippi's curious energy is perfect for morning. Kids get excited without getting chaotic.",
        thumbnail: "🚛",
        duration: "12 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["morning", "learning"],
        youtubeId: "s5-Bh5wW78Q",
        parentRating: 4.4,
        parentReviews: 1450,
        tags: ["blippi", "learning", "morning"],
        workedFor: 80,
        addedBy: "David R.",
      },
      {
        id: "abc-morning",
        title: "ABC Song | Super Simple Songs",
        description: "Learning feels easy in the morning. This cheerful ABC song pairs great with breakfast.",
        thumbnail: "🔤",
        duration: "2 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["morning", "learning"],
        youtubeId: "36IBDpTRVNE",
        parentRating: 4.7,
        parentReviews: 2100,
        tags: ["abc", "morning", "educational"],
        workedFor: 87,
        addedBy: "Teacher Jen",
      },
    ],
  },
];

export const FEATURED_PLAYLISTS = SAMPLE_PLAYLISTS.slice(0, 4);

export const PARENT_PICKS: ContentItem[] = [
  {
    id: "ms-rachel-songs",
    title: "Songs for Littles – Ms. Rachel",
    description: "Speech therapist-approved songs for toddlers. Perfect for language development and bedtime.",
    thumbnail: "🎵",
    duration: "15 min episodes",
    ageGroups: ["1-2", "2-3"],
    moments: ["bedtime", "learning"],
    youtubeId: "NsEJGgXYm5s",
    parentRating: 4.9,
    parentReviews: 2847,
    tags: ["speech", "language", "educational", "songs"],
    workedFor: 94,
    addedBy: "Sarah M.",
  },
  {
    id: "cocomelon-bedtime",
    title: "CoComelon — Bedtime Songs Only",
    description: "Filtered to just the bedtime and calm songs. Skips the energetic ones that backfire at 8pm.",
    thumbnail: "🌙",
    duration: "25 min playlist",
    ageGroups: ["1-2", "2-3"],
    moments: ["bedtime"],
    youtubeId: "CQoUTmJdnMo",
    parentRating: 4.2,
    parentReviews: 3201,
    tags: ["bedtime", "songs", "routine"],
    workedFor: 81,
    addedBy: "Priya N.",
  },
  {
    id: "cosmic-kids-yoga",
    title: "Cosmic Kids Yoga",
    description: "Yoga adventures that calm kids down and stretch them out. Amazing for bedtime prep or after tantrums.",
    thumbnail: "🧘",
    duration: "20 min adventures",
    ageGroups: ["2-3", "3-4", "4-5"],
    moments: ["calm", "bedtime", "active"],
    youtubeId: "HcmHMXJx7xY",
    parentRating: 4.7,
    parentReviews: 1567,
    tags: ["yoga", "calm", "movement", "breathing"],
    workedFor: 89,
    addedBy: "Maria L.",
  },
  {
    id: "baby-shark-pinkfong",
    title: "Baby Shark Dance | Pinkfong",
    description: "The most-watched YouTube video ever. Guaranteed to grab attention and get little ones moving.",
    thumbnail: "🦈",
    duration: "2 min",
    ageGroups: ["1-2", "2-3", "3-4"],
    moments: ["active", "travel", "restaurant"],
    youtubeId: "XqZsoesa55w",
    parentRating: 4.5,
    parentReviews: 5120,
    tags: ["dance", "movement", "catchy"],
    workedFor: 92,
    addedBy: "Community Pick",
  },
  {
    id: "gonoodle-movement",
    title: "GoNoodle Movement & Dance",
    description: "Teacher-approved movement breaks. Perfect for burning energy before it turns into chaos.",
    thumbnail: "💃",
    duration: "5 min videos",
    ageGroups: ["2-3", "3-4", "4-5", "5-6"],
    moments: ["active", "morning"],
    youtubeId: "l4WNrvVjiTw",
    parentRating: 4.7,
    parentReviews: 1450,
    tags: ["movement", "dance", "energy", "school"],
    workedFor: 91,
    addedBy: "Teacher Jen",
  },
  {
    id: "super-simple-abc",
    title: "ABC Song | Super Simple Songs",
    description: "The clearest, most parent-approved ABC song on YouTube. Simple visuals, perfect pacing.",
    thumbnail: "🔤",
    duration: "2 min",
    ageGroups: ["2-3", "3-4", "4-5"],
    moments: ["learning", "morning"],
    youtubeId: "36IBDpTRVNE",
    parentRating: 4.7,
    parentReviews: 2100,
    tags: ["letters", "abc", "educational"],
    workedFor: 90,
    addedBy: "Teacher Jen",
  },
];
