export type Moment =
  | "bedtime"
  | "travel"
  | "calm"
  | "sick-day"
  | "restaurant"
  | "learning"
  | "active"
  | "morning";

export type AgeGroup = "1-2" | "2-3" | "3-4" | "4-5" | "5-6" | "all";

export interface ContentItem {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  duration: string;
  ageGroups: AgeGroup[];
  moments: Moment[];
  youtubeId: string;
  parentRating: number;
  parentReviews: number;
  tags: string[];
  workedFor: number;
  addedBy: string;
}

export interface Playlist {
  id: string;
  title: string;
  description: string;
  cover: string;
  coverEmoji: string;
  moments: Moment[];
  ageGroups: AgeGroup[];
  itemCount: number;
  saves: number;
  createdBy: string;
  parentVerified: boolean;
  tags: string[];
  gradient: string;
  items?: ContentItem[];
}

export const MOMENTS: { id: Moment; label: string; emoji: string; color: string; bg: string }[] = [
  { id: "bedtime", label: "Bedtime Wind-Down", emoji: "🌙", color: "#7C3AED", bg: "#EDE9FE" },
  { id: "travel", label: "Travel & Flights", emoji: "✈️", color: "#0284C7", bg: "#E0F2FE" },
  { id: "calm", label: "Calm & Reset", emoji: "🌿", color: "#059669", bg: "#D1FAE5" },
  { id: "sick-day", label: "Sick Day Comfort", emoji: "🤒", color: "#DC2626", bg: "#FEE2E2" },
  { id: "restaurant", label: "Restaurant Wait", emoji: "🍕", color: "#D97706", bg: "#FEF3C7" },
  { id: "learning", label: "Learning & Growth", emoji: "📚", color: "#2563EB", bg: "#DBEAFE" },
  { id: "active", label: "Move & Dance", emoji: "💃", color: "#DB2777", bg: "#FCE7F3" },
  { id: "morning", label: "Morning Start", emoji: "☀️", color: "#CA8A04", bg: "#FEF9C3" },
];

export const AGE_GROUPS: { id: AgeGroup; label: string }[] = [
  { id: "all", label: "All Ages" },
  { id: "1-2", label: "1–2 yrs" },
  { id: "2-3", label: "2–3 yrs" },
  { id: "3-4", label: "3–4 yrs" },
  { id: "4-5", label: "4–5 yrs" },
  { id: "5-6", label: "5–6 yrs" },
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: "bedtime-wind-down-2yr",
    title: "2-Year-Old Bedtime Wind-Down",
    description: "Calm songs, slow animations, and gentle routines that actually work for toddler bedtime. Parents in our community swear by these.",
    cover: "/playlists/bedtime.jpg",
    coverEmoji: "🌙",
    moments: ["bedtime"],
    ageGroups: ["1-2", "2-3"],
    itemCount: 4,
    saves: 847,
    createdBy: "Sarah M., mom of 3",
    parentVerified: true,
    tags: ["calm", "sleep", "routine", "lullabies"],
    gradient: "from-indigo-500 to-purple-600",
    items: [
      {
        id: "twinkle-ssl",
        title: "Twinkle Twinkle Little Star | Super Simple Songs",
        description: "The definitive Twinkle Twinkle with soft, calming animation. 2.4 billion views — consistently the most-used bedtime video by parents.",
        thumbnail: "⭐",
        duration: "2 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime"],
        youtubeId: "yCjJyiqpAuU",
        parentRating: 4.9,
        parentReviews: 3100,
        tags: ["lullaby", "calm", "bedtime"],
        workedFor: 93,
        addedBy: "Sarah M.",
      },
      {
        id: "cocomelon-twinkle-more",
        title: "Twinkle Twinkle + More Nursery Rhymes | CoComelon",
        description: "CoComelon's bedtime compilation — soft songs, gentle pacing, and familiar faces that comfort toddlers into sleep mode.",
        thumbnail: "🌙",
        duration: "30 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime"],
        youtubeId: "FGcXy0MZ3Ys",
        parentRating: 4.5,
        parentReviews: 2100,
        tags: ["lullaby", "cocomelon", "bedtime"],
        workedFor: 87,
        addedBy: "Priya N.",
      },
      {
        id: "ms-rachel-toddler",
        title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
        description: "Speech therapist-approved songs for toddlers. Calm, language-rich, and genuinely soothing for wind-down time.",
        thumbnail: "🎵",
        duration: "45 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["bedtime", "learning"],
        youtubeId: "h67AgK4EHq4",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["speech", "language", "lullaby"],
        workedFor: 94,
        addedBy: "Sarah M.",
      },
      {
        id: "cosmic-kids-bedtime",
        title: "Frozen | A Cosmic Kids Yoga Adventure",
        description: "A 23-minute yoga adventure that burns off the last of the physical energy and ends with deep breathing — kids fall asleep faster after this.",
        thumbnail: "🧘",
        duration: "23 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["bedtime", "calm"],
        youtubeId: "xlg052EKMtk",
        parentRating: 4.8,
        parentReviews: 1567,
        tags: ["yoga", "calm", "bedtime", "breathing"],
        workedFor: 89,
        addedBy: "Maria L.",
      },
    ],
  },
  {
    id: "flight-safe-toddler",
    title: "Flight-Safe Toddler Videos",
    description: "Holds attention 30+ minutes. These videos worked on a 6-hour flight with a 2-year-old. No WiFi needed for some!",
    cover: "/playlists/travel.jpg",
    coverEmoji: "✈️",
    moments: ["travel"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 1243,
    createdBy: "James K., dad of 2",
    parentVerified: true,
    tags: ["travel", "offline", "long-form", "distraction"],
    gradient: "from-sky-400 to-blue-600",
    items: [
      {
        id: "baby-shark-travel",
        title: "Baby Shark Dance | Pinkfong",
        description: "Most-watched YouTube video ever (16.7B views). Guaranteed to grab attention instantly — perfect for that first 5 minutes of a flight.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["travel", "active"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["catchy", "fun", "travel"],
        workedFor: 92,
        addedBy: "James K.",
      },
      {
        id: "pinkfong-compilation",
        title: "Baby Shark + More Kids Songs | Pinkfong Compilation",
        description: "40-minute Pinkfong compilation — enough to cover takeoff, cruising altitude, and the wait for snacks.",
        thumbnail: "🎶",
        duration: "40 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["travel"],
        youtubeId: "IPf2cA1KUdE",
        parentRating: 4.4,
        parentReviews: 1870,
        tags: ["compilation", "travel", "pinkfong"],
        workedFor: 85,
        addedBy: "James K.",
      },
      {
        id: "ssl-old-macdonald-travel",
        title: "Old MacDonald + More | Super Simple Songs",
        description: "Classic nursery rhymes in a long compilation. Calm, familiar, and works even without headphones.",
        thumbnail: "🐄",
        duration: "60 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["travel", "learning"],
        youtubeId: "lWhqORImND0",
        parentRating: 4.6,
        parentReviews: 1340,
        tags: ["nursery", "compilation", "travel"],
        workedFor: 83,
        addedBy: "David R.",
      },
      {
        id: "cocomelon-travel",
        title: "Twinkle Twinkle + Nursery Rhymes | CoComelon",
        description: "CoComelon's familiar songs keep toddlers calm in unfamiliar places. The recognizable characters are especially comforting mid-flight.",
        thumbnail: "🌈",
        duration: "30 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["travel", "calm"],
        youtubeId: "FGcXy0MZ3Ys",
        parentRating: 4.5,
        parentReviews: 2100,
        tags: ["cocomelon", "familiar", "travel"],
        workedFor: 80,
        addedBy: "Maria L.",
      },
    ],
  },
  {
    id: "calm-down-videos",
    title: "Videos That Calm Tantrums",
    description: "When your toddler is overstimulated or melting down. Breathing songs, slow clips, soft animations — all parent-tested.",
    cover: "/playlists/calm.jpg",
    coverEmoji: "🌿",
    moments: ["calm"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 692,
    createdBy: "Priya N., mom of twins",
    parentVerified: true,
    tags: ["tantrum", "calm", "regulation", "breathing"],
    gradient: "from-emerald-400 to-teal-600",
    items: [
      {
        id: "cosmic-kids-calm",
        title: "Frozen | A Cosmic Kids Yoga Adventure",
        description: "Yoga adventures that calm kids through movement and deep breathing. One of the most recommended post-tantrum reset videos.",
        thumbnail: "🧘",
        duration: "23 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["calm", "bedtime"],
        youtubeId: "xlg052EKMtk",
        parentRating: 4.8,
        parentReviews: 1567,
        tags: ["yoga", "calm", "breathing"],
        workedFor: 89,
        addedBy: "Maria L.",
      },
      {
        id: "gonoodle-calm",
        title: "Banana Banana Meatball | GoNoodle",
        description: "Silly, low-stimulus movement song that redirects energy without ramping kids back up. Great at the start of a calm-down.",
        thumbnail: "🍌",
        duration: "3 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["calm", "active"],
        youtubeId: "BQ9q4U2P3ig",
        parentRating: 4.6,
        parentReviews: 980,
        tags: ["movement", "calm", "redirection"],
        workedFor: 84,
        addedBy: "Priya N.",
      },
      {
        id: "ms-rachel-calm",
        title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
        description: "Slow, warm, speech-rich — Ms. Rachel's calm delivery naturally slows toddlers down. Works mid-meltdown and after.",
        thumbnail: "🎵",
        duration: "45 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["calm", "bedtime"],
        youtubeId: "h67AgK4EHq4",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["calm", "language", "songs"],
        workedFor: 94,
        addedBy: "Sarah M.",
      },
      {
        id: "cocomelon-twinkle-calm",
        title: "Twinkle Twinkle + More Nursery Rhymes | CoComelon",
        description: "Familiar CoComelon songs with gentle pacing. Comfort through familiarity — what toddlers need when they're overwhelmed.",
        thumbnail: "🌙",
        duration: "30 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["calm", "bedtime"],
        youtubeId: "FGcXy0MZ3Ys",
        parentRating: 4.5,
        parentReviews: 1120,
        tags: ["gentle", "familiar", "calm"],
        workedFor: 82,
        addedBy: "Amy T.",
      },
    ],
  },
  {
    id: "sick-day-gentle",
    title: "Low-Stim Sick Day Shows",
    description: "Gentle, quiet, comforting shows toddlers watch without getting wound up. Perfect when your little one is home sick.",
    cover: "/playlists/sickday.jpg",
    coverEmoji: "🤒",
    moments: ["sick-day"],
    ageGroups: ["1-2", "2-3", "3-4", "4-5"],
    itemCount: 4,
    saves: 534,
    createdBy: "Maria L., mom of 1",
    parentVerified: true,
    tags: ["gentle", "quiet", "comforting", "low-stim"],
    gradient: "from-rose-400 to-pink-600",
    items: [
      {
        id: "cocomelon-bath-sick",
        title: "Bath Song | CoComelon Nursery Rhymes",
        description: "7.3 billion views for a reason — the familiar, gentle rhythm is uniquely comforting for unwell toddlers who need reassurance.",
        thumbnail: "🛁",
        duration: "3 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["sick-day", "calm"],
        youtubeId: "WRVsOCh907o",
        parentRating: 4.7,
        parentReviews: 1890,
        tags: ["gentle", "familiar", "comforting"],
        workedFor: 88,
        addedBy: "Maria L.",
      },
      {
        id: "twinkle-sick",
        title: "Twinkle Twinkle Little Star | Super Simple Songs",
        description: "Slow and quiet. Perfect for sick days when you want something calming, not exciting. Soft animation, no jump cuts.",
        thumbnail: "⭐",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["sick-day", "bedtime"],
        youtubeId: "yCjJyiqpAuU",
        parentRating: 4.8,
        parentReviews: 1120,
        tags: ["quiet", "gentle", "low-stim"],
        workedFor: 90,
        addedBy: "Amy T.",
      },
      {
        id: "ms-rachel-sick",
        title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
        description: "Gentle, warm, speech-rich. Perfect for sick days at home — Ms. Rachel's calm voice is genuinely soothing.",
        thumbnail: "🎵",
        duration: "45 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["sick-day", "learning"],
        youtubeId: "h67AgK4EHq4",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["gentle", "educational", "comforting"],
        workedFor: 93,
        addedBy: "Sarah M.",
      },
      {
        id: "cocomelon-twinkle-sick",
        title: "Twinkle Twinkle + Nursery Rhymes | CoComelon",
        description: "Slow-paced, familiar songs for sick toddlers who need comfort. The gentle 3D animation is easy on their eyes.",
        thumbnail: "🌈",
        duration: "30 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["sick-day", "calm"],
        youtubeId: "FGcXy0MZ3Ys",
        parentRating: 4.5,
        parentReviews: 760,
        tags: ["calm", "sick-day", "familiar"],
        workedFor: 79,
        addedBy: "David R.",
      },
    ],
  },
  {
    id: "restaurant-quick-wins",
    title: "5-Minute Restaurant Savers",
    description: "Short, engaging videos for when food is delayed and the meltdown is coming. Calm, not hyper. Tested in real restaurants.",
    cover: "/playlists/restaurant.jpg",
    coverEmoji: "🍕",
    moments: ["restaurant"],
    ageGroups: ["1-2", "2-3", "3-4"],
    itemCount: 4,
    saves: 421,
    createdBy: "David R., dad of 3",
    parentVerified: true,
    tags: ["quick", "engaging", "calm", "public"],
    gradient: "from-amber-400 to-orange-500",
    items: [
      {
        id: "baby-shark-restaurant",
        title: "Baby Shark Dance | Pinkfong",
        description: "Works every single time. Short, catchy, and replayable — fills a 3-minute wait with zero negotiation.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["restaurant", "travel"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["quick", "catchy", "restaurant"],
        workedFor: 92,
        addedBy: "David R.",
      },
      {
        id: "gonoodle-restaurant",
        title: "Banana Banana Meatball | GoNoodle",
        description: "Silly and engaging without being hyperactive. Swap to this after Baby Shark to keep the attention going.",
        thumbnail: "🍌",
        duration: "3 min",
        ageGroups: ["2-3", "3-4", "4-5"],
        moments: ["restaurant"],
        youtubeId: "BQ9q4U2P3ig",
        parentRating: 4.6,
        parentReviews: 890,
        tags: ["silly", "short", "restaurant"],
        workedFor: 83,
        addedBy: "Maria L.",
      },
      {
        id: "ssl-icecream-restaurant",
        title: "The Ice Cream Song | Super Simple Songs",
        description: "A cheerful 3-minute song with familiar counting. Short enough to replay twice while waiting for food.",
        thumbnail: "🍦",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["restaurant", "learning"],
        youtubeId: "KbrSWbuWtmc",
        parentRating: 4.5,
        parentReviews: 790,
        tags: ["short", "cheerful", "restaurant"],
        workedFor: 81,
        addedBy: "Amy T.",
      },
      {
        id: "pinkfong-restaurant",
        title: "Baby Shark + More Kids Songs | Pinkfong Compilation",
        description: "If you need more than 5 minutes, queue this up. 40 minutes of Pinkfong keeps things calm through even the slowest kitchens.",
        thumbnail: "🎶",
        duration: "40 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["restaurant", "travel"],
        youtubeId: "IPf2cA1KUdE",
        parentRating: 4.4,
        parentReviews: 670,
        tags: ["compilation", "restaurant", "backup"],
        workedFor: 80,
        addedBy: "James K.",
      },
    ],
  },
  {
    id: "abc-123-adventures",
    title: "ABC & 123 Adventures",
    description: "Learning letters, numbers, and early concepts through songs and stories that kids actually want to watch again and again.",
    cover: "/playlists/learning.jpg",
    coverEmoji: "📚",
    moments: ["learning"],
    ageGroups: ["2-3", "3-4", "4-5"],
    itemCount: 5,
    saves: 976,
    createdBy: "Teacher Jen, mom of 2",
    parentVerified: true,
    tags: ["educational", "letters", "numbers", "songs"],
    gradient: "from-blue-500 to-violet-600",
    items: [
      {
        id: "ssl-old-macdonald-learn",
        title: "Old MacDonald + More | Super Simple Songs",
        description: "Animal names, sounds, and movement — an hour of early learning through classic nursery rhymes kids love to sing along with.",
        thumbnail: "🐄",
        duration: "60 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["learning", "morning"],
        youtubeId: "lWhqORImND0",
        parentRating: 4.6,
        parentReviews: 1340,
        tags: ["animals", "nursery", "educational"],
        workedFor: 85,
        addedBy: "Teacher Jen",
      },
      {
        id: "cocomelon-old-macdonald",
        title: "Old MacDonald + Baby Animals | CoComelon",
        description: "CoComelon's take on farm animals — vivid, engaging, and educational. Kids absorb animal names and sounds without realizing it.",
        thumbnail: "🐑",
        duration: "30 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["learning"],
        youtubeId: "rHjhg_w09_c",
        parentRating: 4.6,
        parentReviews: 1200,
        tags: ["animals", "colors", "educational"],
        workedFor: 86,
        addedBy: "Teacher Jen",
      },
      {
        id: "cocomelon-colors",
        title: "The Colors Song | CoComelon",
        description: "Bright, clear color teaching through a popsicle song kids beg to rewatch. Most parents say colors clicked after 3-4 viewings.",
        thumbnail: "🎨",
        duration: "30 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["learning"],
        youtubeId: "yP8Qedl1gS0",
        parentRating: 4.5,
        parentReviews: 980,
        tags: ["colors", "educational", "songs"],
        workedFor: 84,
        addedBy: "James K.",
      },
      {
        id: "ssl-icecream-learn",
        title: "The Ice Cream Song | Super Simple Songs",
        description: "Counting 1-5 wrapped in an irresistible ice cream song. Kids count along without being asked — it just happens.",
        thumbnail: "🍦",
        duration: "3 min",
        ageGroups: ["2-3", "3-4"],
        moments: ["learning"],
        youtubeId: "KbrSWbuWtmc",
        parentRating: 4.5,
        parentReviews: 790,
        tags: ["counting", "numbers", "educational"],
        workedFor: 83,
        addedBy: "Maria L.",
      },
      {
        id: "ms-rachel-learn",
        title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
        description: "Speech therapist-designed content that teaches language, words, and early concepts through interactive songs.",
        thumbnail: "🎵",
        duration: "45 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["learning", "bedtime"],
        youtubeId: "h67AgK4EHq4",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["speech", "language", "educational"],
        workedFor: 93,
        addedBy: "Teacher Jen",
      },
    ],
  },
  {
    id: "dance-and-wiggle",
    title: "Dance & Wiggle Time",
    description: "Get the energy OUT before it gets chaotic. Fun, silly dance videos that turn the living room into a dance floor.",
    cover: "/playlists/dance.jpg",
    coverEmoji: "💃",
    moments: ["active"],
    ageGroups: ["1-2", "2-3", "3-4", "4-5", "5-6"],
    itemCount: 4,
    saves: 1102,
    createdBy: "Community Pick",
    parentVerified: true,
    tags: ["energy", "dancing", "movement", "fun"],
    gradient: "from-pink-500 to-fuchsia-600",
    items: [
      {
        id: "baby-shark-dance",
        title: "Baby Shark Dance | Pinkfong",
        description: "The ultimate toddler dance starter. Gets every kid up and moving instantly — no warm-up needed.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["active", "travel"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["dance", "movement", "fun"],
        workedFor: 95,
        addedBy: "Community Pick",
      },
      {
        id: "gonoodle-dance",
        title: "Banana Banana Meatball | GoNoodle",
        description: "Silly movement song that gets kids jumping and laughing. Teacher-approved for burning energy in short bursts.",
        thumbnail: "🍌",
        duration: "3 min",
        ageGroups: ["2-3", "3-4", "4-5", "5-6"],
        moments: ["active"],
        youtubeId: "BQ9q4U2P3ig",
        parentRating: 4.7,
        parentReviews: 1450,
        tags: ["movement", "dance", "energy"],
        workedFor: 91,
        addedBy: "Amy T.",
      },
      {
        id: "pinkfong-dance",
        title: "Baby Shark + More Kids Songs | Pinkfong Compilation",
        description: "40 minutes of Pinkfong energy songs. Queue this up before dinner and let them dance it all out.",
        thumbnail: "🎶",
        duration: "40 min",
        ageGroups: ["1-2", "2-3", "3-4", "4-5"],
        moments: ["active"],
        youtubeId: "IPf2cA1KUdE",
        parentRating: 4.4,
        parentReviews: 1020,
        tags: ["compilation", "dance", "energy"],
        workedFor: 86,
        addedBy: "David R.",
      },
      {
        id: "ssl-icecream-dance",
        title: "The Ice Cream Song | Super Simple Songs",
        description: "A bouncy, cheerful song that naturally makes kids dance. Short enough to replay when the older kids want 'one more'.",
        thumbnail: "🍦",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4", "4-5"],
        moments: ["active", "morning"],
        youtubeId: "KbrSWbuWtmc",
        parentRating: 4.5,
        parentReviews: 830,
        tags: ["bouncy", "fun", "movement"],
        workedFor: 84,
        addedBy: "Maria L.",
      },
    ],
  },
  {
    id: "morning-start-up",
    title: "Happy Morning Starter",
    description: "Cheerful, energizing shows that set a positive tone without the chaos. Great for the TV-while-getting-dressed window.",
    cover: "/playlists/morning.jpg",
    coverEmoji: "☀️",
    moments: ["morning"],
    ageGroups: ["2-3", "3-4", "4-5", "5-6"],
    itemCount: 4,
    saves: 388,
    createdBy: "Amy T., mom of 2",
    parentVerified: true,
    tags: ["morning", "cheerful", "routine", "positive"],
    gradient: "from-yellow-400 to-orange-400",
    items: [
      {
        id: "ssl-icecream-morning",
        title: "The Ice Cream Song | Super Simple Songs",
        description: "Cheerful and upbeat without being chaotic — perfect for the getting-dressed window when you need happy but not wild.",
        thumbnail: "🍦",
        duration: "3 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["morning"],
        youtubeId: "KbrSWbuWtmc",
        parentRating: 4.5,
        parentReviews: 830,
        tags: ["morning", "cheerful", "short"],
        workedFor: 83,
        addedBy: "Amy T.",
      },
      {
        id: "cocomelon-old-macdonald-morning",
        title: "Old MacDonald + Baby Animals | CoComelon",
        description: "Farm animals are a morning hit — bright, cheerful, and a gentle wake-up for little brains.",
        thumbnail: "🐑",
        duration: "30 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["morning", "learning"],
        youtubeId: "rHjhg_w09_c",
        parentRating: 4.6,
        parentReviews: 1200,
        tags: ["morning", "animals", "cheerful"],
        workedFor: 80,
        addedBy: "David R.",
      },
      {
        id: "ms-rachel-morning",
        title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
        description: "A warm, positive start to the day. Ms. Rachel's energy is cheerful without being overwhelming — great morning tone-setter.",
        thumbnail: "🎵",
        duration: "45 min",
        ageGroups: ["1-2", "2-3"],
        moments: ["morning", "learning"],
        youtubeId: "h67AgK4EHq4",
        parentRating: 4.9,
        parentReviews: 2847,
        tags: ["morning", "learning", "positive"],
        workedFor: 87,
        addedBy: "Amy T.",
      },
      {
        id: "baby-shark-morning",
        title: "Baby Shark Dance | Pinkfong",
        description: "For the mornings when you need immediate energy and smiles. 16.7 billion views — some things just work.",
        thumbnail: "🦈",
        duration: "2 min",
        ageGroups: ["1-2", "2-3", "3-4"],
        moments: ["morning", "active"],
        youtubeId: "XqZsoesa55w",
        parentRating: 4.5,
        parentReviews: 5120,
        tags: ["morning", "energetic", "fun"],
        workedFor: 88,
        addedBy: "James K.",
      },
    ],
  },
];

export const FEATURED_PLAYLISTS = SAMPLE_PLAYLISTS.slice(0, 4);

export const PARENT_PICKS: ContentItem[] = [
  {
    id: "ms-rachel-songs",
    title: "Toddler Learning with Ms. Rachel | Nursery Rhymes & Songs",
    description: "Speech therapist-approved songs for toddlers. Perfect for language development and bedtime.",
    thumbnail: "🎵",
    duration: "45 min",
    ageGroups: ["1-2", "2-3"],
    moments: ["bedtime", "learning"],
    youtubeId: "h67AgK4EHq4",
    parentRating: 4.9,
    parentReviews: 2847,
    tags: ["speech", "language", "educational", "songs"],
    workedFor: 94,
    addedBy: "Sarah M.",
  },
  {
    id: "cocomelon-bath",
    title: "Bath Song | CoComelon Nursery Rhymes",
    description: "7.3 billion views. The most comforting CoComelon video — great for sick days, bedtime, and calm moments.",
    thumbnail: "🛁",
    duration: "3 min",
    ageGroups: ["1-2", "2-3"],
    moments: ["bedtime", "sick-day", "calm"],
    youtubeId: "WRVsOCh907o",
    parentRating: 4.7,
    parentReviews: 3201,
    tags: ["bedtime", "comforting", "familiar"],
    workedFor: 88,
    addedBy: "Priya N.",
  },
  {
    id: "cosmic-kids-yoga",
    title: "Frozen | A Cosmic Kids Yoga Adventure",
    description: "Yoga adventures that calm kids down and stretch them out. Amazing for bedtime prep or after tantrums.",
    thumbnail: "🧘",
    duration: "23 min",
    ageGroups: ["2-3", "3-4", "4-5"],
    moments: ["calm", "bedtime", "active"],
    youtubeId: "xlg052EKMtk",
    parentRating: 4.8,
    parentReviews: 1567,
    tags: ["yoga", "calm", "movement", "breathing"],
    workedFor: 89,
    addedBy: "Maria L.",
  },
  {
    id: "baby-shark-pinkfong",
    title: "Baby Shark Dance | Pinkfong",
    description: "The most-watched YouTube video ever. Guaranteed to grab attention and get little ones moving.",
    thumbnail: "🦈",
    duration: "2 min",
    ageGroups: ["1-2", "2-3", "3-4"],
    moments: ["active", "travel", "restaurant"],
    youtubeId: "XqZsoesa55w",
    parentRating: 4.5,
    parentReviews: 5120,
    tags: ["dance", "movement", "catchy"],
    workedFor: 92,
    addedBy: "Community Pick",
  },
  {
    id: "gonoodle-movement",
    title: "Banana Banana Meatball | GoNoodle",
    description: "Teacher-approved movement breaks. Perfect for burning energy before it turns into chaos.",
    thumbnail: "🍌",
    duration: "3 min",
    ageGroups: ["2-3", "3-4", "4-5", "5-6"],
    moments: ["active", "morning"],
    youtubeId: "BQ9q4U2P3ig",
    parentRating: 4.7,
    parentReviews: 1450,
    tags: ["movement", "dance", "energy"],
    workedFor: 91,
    addedBy: "Teacher Jen",
  },
  {
    id: "ssl-old-macdonald",
    title: "Old MacDonald + More | Super Simple Songs",
    description: "An hour of classic nursery rhymes with clear animation. Animal names, sounds, and counting — all in one.",
    thumbnail: "🐄",
    duration: "60 min",
    ageGroups: ["1-2", "2-3", "3-4"],
    moments: ["learning", "morning"],
    youtubeId: "lWhqORImND0",
    parentRating: 4.6,
    parentReviews: 1340,
    tags: ["animals", "nursery", "educational"],
    workedFor: 85,
    addedBy: "Teacher Jen",
  },
];
